/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client_Side;

import Exceptions.FTPException;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.Socket;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mason
 */
public class ClientGUI extends javax.swing.JFrame {

    
          //Thread that will take care of updating playlist
    static ChatManager chatmanager;

    //RTP variables:
    //----------------
    DatagramPacket rcvdp;               //UDP packet received from the server
    static DatagramSocket RTPsocket;    //socket to be used to send and receive UDP packets
    static int RTP_RCV_PORT = 5544;     //port where the client will receive the RTP packets
    static StreamProcessorClient sp;
    static String IPAddress;
    
    //RTSP variables
    //----------------
    //rtsp states 
    final static int INIT = 0;
    final static int READY = 1;
    final static int PLAYING = 2;
    final static int PAUSED = 3;
    static int state;                   //RTSP state == INIT or READY or PLAYING

    static String SongFileName;         //song file to request to the server
    static int RTSPSeqNb = 0;           //Sequence number of RTSP messages within the session
    static int RTSPid = 0;              //ID of the RTSP session (given by the RTSP Server)

  

    final static String CRLF = "\r\n";
    

    //Audio constants:
    //------------------
    static int MJPEG_TYPE = 14; //RTP payload type for MP3  audio
    /**
     * Creates new form HostGUI
     */
    public ClientGUI() throws IOException {
        initComponents();
        tPane.paintComponent(this.getGraphics());
        lb_ArtistName.setText(" ");
        lb_SongName.setText(" ");
        lb_AlbumName.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Play = new javax.swing.JButton();
        btn_Download = new javax.swing.JButton();
        btn_upload = new javax.swing.JButton();
        tb_chatInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_ChatWindow = new javax.swing.JTextArea();
        btn_SendMessage = new javax.swing.JButton();
        lb_Artist = new javax.swing.JLabel();
        lb_ArtistName = new javax.swing.JLabel();
        lb_SongName = new javax.swing.JLabel();
        lb_Song = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_Album = new javax.swing.JLabel();
        lb_AlbumName = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_PlayListArea = new javax.swing.JTextArea();
        tPane = new Client_Side.TPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MuZe Streaming");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.white);
        setName("frm_MuZe"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btn_Play.setText("Pause");
        btn_Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PlayActionPerformed(evt);
            }
        });

        btn_Download.setText("Download");
        btn_Download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DownloadActionPerformed(evt);
            }
        });

        btn_upload.setText("Upload");
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });

        tb_chatInput.setText("Enter Message Here");
        tb_chatInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_chatInputActionPerformed(evt);
            }
        });

        txta_ChatWindow.setEditable(false);
        txta_ChatWindow.setColumns(20);
        txta_ChatWindow.setRows(5);
        txta_ChatWindow.setFocusable(false);
        jScrollPane1.setViewportView(txta_ChatWindow);

        btn_SendMessage.setText("Send Message");
        btn_SendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SendMessageActionPerformed(evt);
            }
        });

        lb_Artist.setText("Artist:");

        lb_ArtistName.setText("jLabel1");

        lb_SongName.setText("jLabel1");

        lb_Song.setText("Song:");

        lb_Album.setText("Album:");

        lb_AlbumName.setText("jLabel1");

        txt_PlayListArea.setEditable(false);
        txt_PlayListArea.setColumns(20);
        txt_PlayListArea.setRows(5);
        jScrollPane3.setViewportView(txt_PlayListArea);

        tPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tPane.setPreferredSize(new java.awt.Dimension(300, 216));

        javax.swing.GroupLayout tPaneLayout = new javax.swing.GroupLayout(tPane);
        tPane.setLayout(tPaneLayout);
        tPaneLayout.setHorizontalGroup(
            tPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        tPaneLayout.setVerticalGroup(
            tPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(tb_chatInput)
                    .addComponent(btn_SendMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Play, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_Artist)
                                    .addComponent(lb_Song)
                                    .addComponent(lb_Album))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_ArtistName, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_AlbumName)
                                            .addComponent(lb_SongName))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Download, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(btn_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_Artist)
                                    .addComponent(lb_ArtistName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_Song)
                                    .addComponent(lb_SongName))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_Album)
                                    .addComponent(lb_AlbumName)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78)
                        .addComponent(jLabel5)
                        .addGap(88, 88, 88)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_chatInput, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btn_SendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Play, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Download, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PlayActionPerformed
        if (sp != null )
        {
            try {
                sp.pause();
            } catch (InterruptedException ex) {
                Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(btn_Play.getText() == "Play") {
                
                btn_Play.setText("Pause");
                
            }
            else{
                
                btn_Play.setText("Play");
                
            }
            
        }
    }//GEN-LAST:event_btn_PlayActionPerformed

    private void btn_DownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DownloadActionPerformed
       DownloadGUI dlGUI = new DownloadGUI(IPAddress);
    }//GEN-LAST:event_btn_DownloadActionPerformed

    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
        // TODO add your handling code here:
        UploadGUI upGui = new UploadGUI();
    }//GEN-LAST:event_btn_uploadActionPerformed

    private void tb_chatInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_chatInputActionPerformed
        if(tb_chatInput.getText() == "Enter Message Here") {
            
            tb_chatInput.setText("");
            
        }
    }//GEN-LAST:event_tb_chatInputActionPerformed

    private void btn_SendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SendMessageActionPerformed
        try
        {
            // TODO add your handling code here:
            chatmanager.sendMessage(tb_chatInput.getText());
        } catch (IOException ex)
        {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_SendMessageActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnknownHostException, IOException, FTPException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ClientGUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

            //get server RTSP port and IP address
            int RTSP_server_port = 5544;
            
            String serverHost = getIPAddress();
            
            InetAddress ServerIPAddr = InetAddress.getByName(serverHost);
            
            String username = (String)JOptionPane.showInputDialog(
                    null,
                    "Enter the your username:",
                    "UserName",
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    null,
                    "username");
           
            
            
            Socket RTSPsocket = new Socket(ServerIPAddr, RTSP_server_port);
            RTPsocket = new DatagramSocket(RTP_RCV_PORT);
            sp = new StreamProcessorClient(RTPsocket);
            sp.start();
            chatmanager = new ChatManager(IPAddress, txta_ChatWindow, lb_ArtistName, lb_SongName, lb_AlbumName, username);
            chatmanager.start();
            
            
            
            FTPUtil ftp = new FTPUtil(IPAddress, 21, "user", "password");
            ftp.connect();
            
            String [] filenames = ftp.getFileList();
            for(int i = 0; i< filenames.length; i ++)
            {
                txt_PlayListArea.append(filenames[i]);
                txt_PlayListArea.setText(txt_PlayListArea.getText() + "\n");
            
            }
            
    }

  
  private static String getIPAddress() { 
    
        IPAddress = (String)JOptionPane.showInputDialog(
                 null,
                    "Enter the server ip:",
                    "ServerIP",
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    null,
                    "127.0.0.1");
        return IPAddress;
        
    }
          
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Download;
    private javax.swing.JButton btn_Play;
    private javax.swing.JButton btn_SendMessage;
    private javax.swing.JButton btn_upload;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_Album;
    private static javax.swing.JLabel lb_AlbumName;
    private javax.swing.JLabel lb_Artist;
    private static javax.swing.JLabel lb_ArtistName;
    private javax.swing.JLabel lb_Song;
    private static javax.swing.JLabel lb_SongName;
    private Client_Side.TPane tPane;
    private javax.swing.JTextField tb_chatInput;
    private static javax.swing.JTextArea txt_PlayListArea;
    private static javax.swing.JTextArea txta_ChatWindow;
    // End of variables declaration//GEN-END:variables
}
